# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 823fabfccab8ee3dfda0e6e6f4abf0c4822c2378f4e16773e4ca310667e525350f19ce37aa727464482fcdd9c9ff05661bd540f29a6894f3578ec286366990b3

test:
  secret_key_base: 6cc3fe5f680a8bdb3d33056675fcd0e878edfa5cbdd5737845644c315efc6ba1041bfb62029b9f10266674be87d417327650ad0bbc852644daf8be28ee7696b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
